### db config
spring:
  jpa:
    open-in-view: false
    show-sql: true
  datasource:
    main:
      type: com.zaxxer.hikari.HikariDataSource
      maximumPoolSize: 10
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/mytest
      username: root
      password: root